### PR TITLE
Online DB update

### PR DESCRIPTION
**Pull request by bucanero**
You'll find the following changes:

 - online DB feature (added main icon and menu)
 - update offline DB (added option in `Options` menu)
 - ~~updated Mamba loader to 4.84.2~~
 - added/updated the '.ncl' cheat files
 - improved game list browsing (added L1/L2 & R1/R2 triggers to move faster trough the list)
 - included modded plugin binary from @haxxxen

**Notes:**

I've moved all the `.ncl` files to a new folder, `/docs/codes` , as I'm using GitHub pages to host all the codes for the Online DB feature. (the domain `artemis.psdev.tk` points to the github pages)

I've included this updated plugin binary made by @haxxxen, I've the source code and I can also submit another pull request if you want to review it. (as I don't have the Cell SDK I couldn't build it myself)

I also moved the custom `libfont` into the source code, and did some small fixes there.

Just in case, I'm using the Psl1ght lib on macOS, so I only updated the `Makefile`. I assume you'd have to update the Visual Studio project files to compile the updated project.

### CODE REVIEW

**Comment by Dnawrkshp** [comment]
Attempting to build the Artemis-GUI project and it's failing on:

```
cc1.exe: error: unrecognized command line option "-Wformat-truncation=0"
```

What version of PSL1GHT are you on? I think mine is pretty old.

**Comment by bucanero** [comment]
> Attempting to build the Artemis-GUI project and it's failing on:
> 
> ```
> cc1.exe: error: unrecognized command line option "-Wformat-truncation=0"
> ```
> 
> What version of PSL1GHT are you on? I think mine is pretty old.

hello @Dnawrkshp ,

I'm using the latest version, built from source from the https://github.com/ps3dev/ps3toolchain repository. Those scripts should work fine with Linux and macOS, but I'm not sure if it needs some adjustments to be built on Windows. (as far as I understand, with Cygwin it should compile)

btw, I also have some pre-built PSL1GHT toolchains for Linux and macOS here: https://github.com/bucanero/ps3toolchain/releases

Regarding the `-Wformat-truncation=0`, you can safely remove it, it's only an option to remove some warnings on my `gcc` compiler.
Still, I'm not sure if it will compile as it might be using some functions and calls only available with the current psl1ght.

**Comment by bucanero** [comment]
also, my apologies for sending a PR directly from my master branch. I should have done a branch and only send a PR with the discussed changes. I kept working on my master branch and now more changes show up.

**Comment by Dnawrkshp** [comment]
No worries I don't really mind.

I'm trying to build a docker image with the latest psl1ght right now. Hopefully it works and I can build it on the latest sdk.

**Comment by bucanero** [comment]
> I'm trying to build a docker image with the latest psl1ght right now. Hopefully it works and I can build it on the latest sdk.

that sounds great! let me know if you have any questions about my changes or if I can help with the psl1ght stuff

**Comment by Dnawrkshp** [comment]
@bucanero Hey I'm missing ps3mapi.h, is there a library I need to install? I see it's in webman-MOD but I can't find a lib with it.

**Comment by Dnawrkshp** [comment]
Nevermind I was able to find the libraries on your github. 

It compiles! Just need to hook up my ps3 and test it out.

**Comment by bucanero** [comment]
> Nevermind I was able to find the libraries on your github.

👍  I was thinking about the PS3MAPI library but forgot to mention it

The idea behind using that library was to remove all the Mamba/Prx loader from Artemis, since all current CFW and even PS3HEN supports Cobra and PS3Mapi natively. 
The library keeps all the logic about the syscalls, and provides some functions to check/ load/ unload custom `prx` plugins.

To summarize:
- I removed all the code related to Mamba/PRX loader
- used PS3MAPI lib to load/unload artemis plugin

> 
> It compiles! Just need to hook up my ps3 and test it out.

that's great news! 😄 

some additional comments:
- if you place the [cheatdb.zip](https://github.com/bucanero/ArtemisPS3/blob/master/docs/cheatdb.zip) file in `/USRDIR/CACHE/`, when you launch Artemis GUI it will unzip the file to the local code database. I include that `.zip` when I build the release .pkg, so the user doesn't need to copy the cheats to the PS3 manually.
- I added a "plugin selection" to the `Options` menu. It allows the user to select between your original Artemis r5 plugin, and the modded plugin "r6" by haxxxen. In my case, I had much better results using your original r5 plugin, and the "mod" gave me many issues. A few users using DEX firmwares said that the "mod" version worked better for them, but I don't have such PS3 so I can't confirm. I think my mistake was to make the "mod" plugin the default one when you install the .pkg. I want to update the code so the original r5 plugin is the default one, unless the user really wants to experiment.

Plugin-wise, I think it would be nice to integrate the Artemis cheat functions with webman-Mod, that would remove the need to load/unload plugins, and could probably simplify or reduce the memory limits when users loads game + artemis + webman.
For that task I'd have to really improve my skills with the Cell SDK and the whole `.sprx` topic.

Anyways, thanks for your amazing work with Artemis, I still use it and brings a lot of fun when playing on the PS3

**Pull request closed without merging**
